### ISSUE TITLE
IE problem (does not display 1 out of 3)

### ISSUE THREAD

**Issue by kidsil** [kolanos/kohana-captcha#3]
every once in a while (avg 1 out of 3) on IE8 & IE7 the captcha doesn't display, as shown on pic 
http://i43.tinypic.com/9fw1af.png

**Comment by kolanos** [comment]
Fix proposed in Issue #2.

**Comment by Daijobou** [comment]
No thats not fix it. Issue #2 was for long loading time.

With actual version I get in IE8 the same bug.
In Firefox 3.6.3 the captcha very often don't full display. => http://i43.tinypic.com/foluoh.jpg (height is 50)
In Opera its working fine.
