### ISSUE TITLE
Safari browser does not render the captcha image if Content-Length header is sent

### ISSUE THREAD

**Issue by josua** [kolanos/kohana-captcha#6]
First, thank you kolanos for your port of the captcha module for kohana v3.

I am actually doing a cross-browser web application, and the captcha image does not render in Safari 4.5 or 5.0 on windows.
It works well and renders on the following browsers : chrome, explorer, firefox, flock, sea-monkey, opera and netscape.

I have tried to figure out from where the problem was coming and I finally found that it was the content-length header which causes the bug in safari.

in /modules/captcha/classes/controller/captcha.php (line 4)

$captcha = Captcha::instance($group)->render(FALSE);

$this->request->headers['Content-Type'] = File::mime($captcha);

$this->request->headers['Connection'] = 'close';

$this->request->headers['Content-length'] = filesize($captcha);

$this->request->response = $captcha;

Perhaps a problem with the image filesize calculation.
(Note that I have tried to use either a gif or a png background and had the same bug for both mime types.)

Commenting the line which sets the content-length header or not sending it if the user agent is safari, will both fix the bug.
Here is my Bug fix :-)

1- lazy : Comment the following line

// $this->request->headers['Content-length'] = filesize($captcha);

2- better: Replace with the following code

// If the user agent is safari, don't send the content-length header

if( ! preg_match('/safari/i', strtolower($_SERVER['HTTP_USER_AGENT']) ) ){

$this->request->headers['Content-length'] = filesize($captcha);

}

**Comment by kolanos** [comment]
I'm wondering if the headers are out of sequence, does the following work?

$this->request->headers['Content-Type'] = File::mime($captcha);
$this->request->headers['Content-length'] = filesize($captcha);
$this->request->headers['Connection'] = 'close';

I can't test in Safari as I am running Ubuntu.

**Comment by josua** [comment]
Just tested,
Unfortunately, the sequence order don't seem to be in cause. Doesn't work in safari !

But it is surely a better and more logical design to set the connection close header at the end. :-)

**Comment by kolanos** [comment]
I am going to do some research on known HTTP header issues with Safari and try to get to the bottom of this, I don't like the idea of doing browser-by-browser header handling as I think that could get messy very quickly. Hopefully you're not the only one who's experiencing this Content-length bug.

**Comment by kolanos** [comment]
Ok, what I've found so far is a multitude of issues reported about Safari (and other Webkit browsers) handling of the Content-Length header. Apparently it is considered "unsafe" by Safari. For the time being I've decided to comment it out and plan to remove it unless I can find a good reaosn to keep it (and implementing a Safari exception). From what I've read it isn't a required. Change commited here e18479fe5297dd6f3f52f62be6654c31c5b93422.

**Comment by josua** [comment]
Hi kolanos,

I took some time today to debug the captcha module. In fact i found many errors:

First you are trying to compute the image file size with the php filesize function, to set the content-length header:

int filesize ( string $filename )
   $filename Path to the file.
   Gets the size for the given file.

Which as you can see takes a string filename (the path to the file on drive) parameter, and not an image ressource in memory. So this won't work unless you save the image to a file on disk.

But the real bug came from the fact that you are assuming on the following line,

$captcha = Captcha::instance($group)->render(FALSE);

that the render method is returning you the image resource, but this is incorrect since the render function output the image ressource and returns void when it is passed FALSE.

The render function use gd imagepng() or imagegif() or ... which outputs the image and returns a boolean TRUE on success or FALSE on failure.

imagepng — Output a PNG image to either the browser or a file
bool imagepng ( resource $image [, string $filename [, int $quality [, int $filters ]]] )
Outputs or saves a PNG image from the given image.

imagegif — Output image to browser or file
bool imagegif ( resource $image [, string $filename ] )

So every line in the captcha controller after 
$captcha = Captcha::instance($group)->render(FALSE);
are not processed and no headers are sent but the connection close one, since the two following line are incorrect: ($captcha does not contain anything)

$this->request->headers['Content-Type'] = File::mime($captcha);
$this->request->headers['Content-length'] = filesize($captcha); 

I know that it is impossible to dump inside the captcha controller, so it is like blind programming, and it is difficult to see errors or to debug anything.

But if you use the live http header extension for mozilla firefox you will notice that the headers are not sent correctly. In safari and chrome you can also see the captcha image resource headers which are not set correctly. (ressources tab when you inspect an element in safari and chrome)

So I have slightly modified the code of the captcha module and have corrected all the bugs:

Here are my bug fixes:

---

## class Captcha, no change but the render method which is no longer abstract and is called by drivers subclasses [in their render method]. Note that image_render method is no more needed and replaced by render method functionality

```
/**
 * Render the captcha image
 *
 * @param    boolean   $html   If TRUE, returns the html image tag string
     *                                          If FALSE, outputs the image headers and resource to the browser (returns void)
 * @return   mixed             the html image tag element string
 *                             or void (and output the image resource)
 */
public function render($html=TRUE)
{
    if( $html === TRUE )
    {
        // I suggest using the complete url with protocol domain controller action and group name
        $url = URL::site('captcha/index/'.Captcha::$config['group'], TRUE);

        // Or if you prefer relative url
        // $url = URL::site('captcha/index/'.Captcha::$config['group']);

        // Returns the html img tag element
        return '<img src="'.$url.'" width="'.Captcha::$config['width'].'" height="'.Captcha::$config['height'].'" alt="Captcha" class="captcha" />';

    }
    else // Output the image headers and ressource to the browser
    {
        // Pick the correct output function
        $function = 'image'.$this->image_type;

        // Send the correct HTTP headers
        Request::instance()->headers['Content-Type'] = 'image/'.$this->image_type;
        Request::instance()->headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0';
        Request::instance()->headers['Pragma'] = 'no-cache';
        Request::instance()->headers['Connection'] = 'close';

        // Output the image ressource
        $function($this->image);

        // Free up the image resource from memory
        imagedestroy($this->image);
    }
}
```

---

## For the Captcha drivers [subclasses](Captcha_Basic, Captcha_Alpha, Captcha_Black) here is the design pattern. No other changes but the render method, which uses now  an if( $html !== TRUE ) {} block to provide the image to be created twice by the to render calls (from view to render html img tag string and from controller to output the image resource to the browser), and now  returns parent::render($html); instead of $this->image_render($html);

class Captcha_Basic extends Captcha 
{
    /**
     \* Outputs the Captcha image.
     *
     \* @param    boolean   $request   TRUE to output the html image tag
     \*                                FALSE to output the image ressource
     \* @return   mixed
     */
    public function render($html = TRUE)
    {
        if( $html !== TRUE )
        {
                 // put here the code which creates the image
                 ...
        }

```
    // If $html is TRUE, returns (string) the html image tag element
    // If $html is FALSE, output the image headers and resource to the browser (returns void)
    return parent::render($html);
}
```

}

---

## Here is the new captcha controller

class Controller_Captcha extends Controller {

```
/**
 * @var boolean Auto render template
 **/
public $auto_render = FALSE;

/**
 * Output the Captcha challenge image headers and resource to the browser
 *
 * @param string $group Config group name
 */
public function action_index($group = 'default')
{
    Captcha::instance($group)->render(FALSE);
}
```

} // End Controller_Captcha

---

## And Perhaps, advise the user to  set a route in bootstrap.php 

Route::set('captcha', 'captcha(/&lt;action&gt;(/&lt;group&gt;(/&lt;ignore&gt;)))', array('action'=>'index', 'ignore'=>'.*'))->defaults(array(
            'controller' => 'captcha',
            'action' => 'index',

##             'group' => 'default'));

Et Voilà !

Tell me if you prefer that i send you the 3 complete sources by email.

**Comment by kolanos** [comment]
Hey joshua,

Appreciate you taking the time to look into this. The reason why the image_render() method exists is that there are text-bsaed captchas (Riddle, Math). Text-based captchas just bypass the image_render() method. I'll look into implementing some of your other suggestions though.
