### ISSUE TITLE
Session issue - illegal chars

### ISSUE THREAD

**Issue by pdanysz** [kolanos/kohana-captcha#7]
Hi,

I had some problems with $session_type in this module.
In Config file I was using $session_type = 'database' - be cause I'm using a database to store Sessions.

When Page wiith Captha was loaded, and I click anchor to another page without Captcha (leaving the form), I allways recived this error:
"The session id contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,'"

So, I was looking for solution, and I found it. The problem with session was with the "$session_type" parameter. I changed some code in Core file "captcha.php", and its start to run petty well.

Below it's my solusion:
Before:
<code>
Session::instance(Captcha::$config['session_type'])->set('captcha_response', sha1(strtoupper($this->response)));
</code>
After:
<code>
Session::instance()->set('captcha_response', sha1(strtoupper($this->response)));
</code>

Resume:
I changed ALL "Session::instance(Captcha::$config['session_type'])" to Session::instance() and the problem was solved;

**Comment by kolanos** [comment]
Hi pdanysz,

The session_type was in place before you could set a default session type. I will be removing it in the next commit. Thanks!
